language: java
sudo: false
script: mvn clean install
deploy:
  provider: releases
  api_key: "7ac91d81699c73bc6e772d4dd6f0f282d47e25b7"
  file: "Jump-Solider-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
branches:
    only:
    - master
