language: java
sudo: false
script: mvn clean install
deploy:
  provider: releases
  api_key: "9eb94a95408903314e3298748532ac9556590aba"
  file: "Jump-Solider-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: false
